# Bloc 3 — Transformations & Feature Engineering
Objectifs: créer des colonnes calculées, transformer les types, manipuler les chaînes (.str), manipuler les dates (.dt), trier

In [47]:
import numpy as np
import pandas as pd

In [77]:
products = pd.read_csv('../01_data/raw/thelook_products.csv')
sales = pd.read_csv('../01_data/exercises/thelook_sales.csv')
orders = pd.read_csv('../01_data/raw/thelook_orders.csv')

## 1. Ajouter et modifier des colonnes
On travaille souvent avec des colonnes qui n'existent pas encore dans le dataset. Il faut les créer.

### Créer une colonne calculée

In [49]:
products['marge'] = products['retail_price'] - products['cost']

# la nouvelle colonne apparait à droite
products.head()

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id,marge
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Tommy Hilfiger,Women,6.57,10.31,SKU-00001,5,3.74
1,2,Hurley Pro Shorts,Shorts,Hurley,Women,20.85,37.55,SKU-00002,6,16.70
2,3,Columbia Sport Tops & Tees,Tops & Tees,Columbia,Men,21.34,44.52,SKU-00003,9,23.18
3,4,Volcom Classic Leggings,Leggings,Volcom,Women,14.98,42.24,SKU-00004,2,27.26
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Hurley,Women,89.58,149.11,SKU-00005,5,59.53

### Renommer ajouter et supprimer des colonnes

In [52]:
# imaginer que le nom des colomnes n'arriveront jamais bien formatés. 
# Une bonne pratique en base de donné et dataset est d'utiliser le snake_case
products = products.rename(columns={'retail_price': 'retail_price_euro'})
products = products.rename(columns={'sku': 'reference'})
products.head()

,id,name,category,brand,department,cost,retail_price_euro,reference,distribution_center_id,marge
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Tommy Hilfiger,Women,6.57,10.31,SKU-00001,5,3.74
1,2,Hurley Pro Shorts,Shorts,Hurley,Women,20.85,37.55,SKU-00002,6,16.70
2,3,Columbia Sport Tops & Tees,Tops & Tees,Columbia,Men,21.34,44.52,SKU-00003,9,23.18
3,4,Volcom Classic Leggings,Leggings,Volcom,Women,14.98,42.24,SKU-00004,2,27.26
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Hurley,Women,89.58,149.11,SKU-00005,5,59.53

In [53]:
# Mais il vous sera aussi nécessaire de créer vos propres colonnes
# Ici, on change également le type
products['ref_id'] = products['reference'] + products['id'].astype(str)
products.info()

# Pourquoi doit-on caster le type de la colonne ['id']? 
# Essayer sans pour voir...

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2000 non-null   int64
 1   name                    2000 non-null   str
 2   category                2000 non-null   str
 3   brand                   2000 non-null   str
 4   department              2000 non-null   str
 5   cost                    2000 non-null   float64
 6   retail_price_euro       2000 non-null   float64
 7   reference               2000 non-null   str
 8   distribution_center_id  2000 non-null   int64
 9   marge                   2000 non-null   float64
 10  ref_id                  2000 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 172.0 KB

In [59]:
# Il peut aussi arriver que vous deviez supprimer des colonnes inutiles ou pour créer un dataset alternatif
products = products.drop(columns=['brand'])
products.head()

,id,name,category,department,cost,retail_price,sku,distribution_center_id
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Women,6.57,10.31,SKU-00001,5
1,2,Hurley Pro Shorts,Shorts,Women,20.85,37.55,SKU-00002,6
2,3,Columbia Sport Tops & Tees,Tops & Tees,Men,21.34,44.52,SKU-00003,9
3,4,Volcom Classic Leggings,Leggings,Women,14.98,42.24,SKU-00004,2
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Women,89.58,149.11,SKU-00005,5

In [ ]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2000 non-null   int64
 1   name                    2000 non-null   str
 2   category                2000 non-null   str
 3   department              2000 non-null   str
 4   cost                    2000 non-null   float64
 5   retail_price            2000 non-null   float64
 6   reference               2000 non-null   str
 7   distribution_center_id  2000 non-null   int64
 8   marge                   2000 non-null   float64
 9   ref_id                  2000 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 156.4 KB

### Mini-exercice : à vous !

In [ ]:
# Créez une colonne 'taux_marge' = marge / retail_price * 100
# products['taux_marge'] = 

# Affichez les 3 premières lignes

SyntaxError: invalid syntax (3821425523.py, line 2)

## 2. Transformer les types (dtypes)
Quand on charge un CSV, pandas devine les types. Parfois il se trompe. Il faut savoir corriger.

### Vérifier les types actuels

In [ ]:
# Que remarquez-vous sur created_at ?
print(orders.dtypes)

### Convertir avec .astype()

Nous avons vu précédemment que Python possède ses propres fonction pour changer le type de data dúne variable.Pandas a sa propre méthode pour se faire: `.astype()`

In [60]:
print("Avant :", products['id'].dtype)
products['id'] = products['id'].astype(str)
print("Après :", products['id'].dtype)

Avant : int64
Après : str

### Forcer la conversion numérique : pd.to_numeric()

In [63]:
s = pd.Series(['10', '20', 'oops', '40'])
s.info()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      str
dtypes: str(1)
memory usage: 164.0 bytes

In [71]:
# Pour transformer nos strings, on utilise la fonction pd.to_numeric()
# errors='coerce' transforme les erreurs en NaN au lieu de planter
s_numeric = pd.to_numeric(s, errors='coerce')
s_numeric

0        6.57
1       20.85
2       21.34
3       14.98
4       89.58
        ...
1995     3.78
1996    21.10
1997    20.76
1998    25.23
1999    23.36
Name: cost, Length: 2000, dtype: float64

### Convertir les dates : pd.to_datetime()

In [78]:
# On va utiliser ici le dataset `orders` que vous avez chargé plus tôt.
# Observons son data type:

#orders.

# Quel est le type de delivered_at? returned_at?

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  str
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
dtypes: int64(3), str(5)
memory usage: 1.2 MB

In [114]:
# Ceci est un cas typique où vous aurez des datetime ou des timestamps qui arriveront sous forme d'objets ou string.
orders['created_at'] = pd.to_datetime(orders['created_at'])

print(orders['created_at'].dtype)  # on doit trouver: datetime64
orders.info()

datetime64[us]
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  datetime64[us]
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
dtypes: datetime64[us](1), int64(3), str(4)
memory usage: 1.2 MB

## 3. Manipuler le texte avec .str
Pandas offre un accesseur `.str` qui permet d'appliquer des opérations texte à toute une colonne d'un coup.

### Changer le format

In [81]:
# tout en minuscules, le plus souvent utilisé dans le code. Qui aime se faire hurler dessus en capitale par son code?
lower = products['name'].str.lower().head(3)
lower

0    tommy hilfiger regular fit underwear
1                       hurley pro shorts
2              columbia sport tops & tees
Name: name, dtype: str

In [84]:
# ici en MAJUSCULE
upper = products['name'].str.upper().head(3)
upper

0    TOMMY HILFIGER REGULAR FIT UNDERWEAR
1                       HURLEY PRO SHORTS
2              COLUMBIA SPORT TOPS & TEES
Name: name, dtype: str

In [82]:
# Et Là ?
title = products['name'].str.title().head(3)
title

0    Tommy Hilfiger Regular Fit Underwear
1                       Hurley Pro Shorts
2              Columbia Sport Tops & Tees
Name: name, dtype: str

### Chercher dans le texte

In [108]:
# Combien de produits contiennent le mot 'Slim' ?
slim = products['name'].str.contains(('Slim'), na=False)
print(slim.sum())

# Et si je ne sais pas si j'ai SLIM, Slim, ou slim ?

161

### Nettoyer le texte

In [112]:
# Explique que fait on ici:
nettoye = products['name'].str.strip().str.replace('  ', '')
nettoye.head()

0    Tommy Hilfiger Regular Fit Underwear
1                       Hurley Pro Shorts
2              Columbia Sport Tops & Tees
3                 Volcom Classic Leggings
4          Hurley Urban Outerwear & Coats
Name: name, dtype: str

## 4. Manipuler les dates avec .dt

### Extraire les composantes d'une date
Par défaut, lors de la lecture d'un fichier (ex: CSV), Pandas importe les dates sous forme de simples chaînes de caractères (object ou str).

Sous forme de texte, vous ne pouvez pas:
- effectuer de calculs temporels 
- extraire facilement des composants de date (example: jour, mois etc...)

Une fois la colonne convertie en datetime, on peut en extraire plein d'informations.

In [118]:
# Chaque composante devient une nouvelle colonne utilisable pour l'analyse

orders['annee'] = orders['created_at'].dt.year
orders['mois'] = orders['created_at'].dt.month
orders['jour_semaine'] = orders['created_at'].dt.day_name()
orders.head()

,order_id,user_id,status,created_at,num_of_item,shipped_at,delivered_at,returned_at,annee,mois,jour_semaine
0,1,405,Complete,2023-03-15 00:52:04,2,2023-03-17 00:52:04,2023-03-25 00:52:04,NaN,2023,3,Wednesday
1,2,1792,Complete,2024-06-29 13:30:52,3,2024-07-02 13:30:52,2024-07-05 13:30:52,NaN,2024,6,Saturday
2,3,2908,Complete,2024-02-17 14:38:01,1,2024-02-19 14:38:01,2024-02-28 14:38:01,NaN,2024,2,Saturday
3,4,370,Processing,2024-08-01 21:04:12,2,NaN,NaN,NaN,2024,8,Thursday
4,5,97,Returned,2023-12-23 09:01:16,3,2023-12-24 09:01:16,2023-12-31 09:01:16,2024-01-23 09:01:16,2023,12,Saturday

In [120]:
# Vérifiez le type des nouvelles colonnes créées
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  datetime64[us]
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
 8   annee         20000 non-null  int32
 9   mois          20000 non-null  int32
 10  jour_semaine  20000 non-null  str
dtypes: datetime64[us](1), int32(2), int64(3), str(5)
memory usage: 1.5 MB

### Calculer un écart entre deux dates

In [121]:
# Rappel de conversion str -> datetime type
orders['shipped_at'] = pd.to_datetime(orders['shipped_at'])

# Le résultat est un timedelta, .dt.days donne le nombre de jours
# on peut utiliser de simple operator comme '-' ou '+'
orders['delai'] = (orders['shipped_at'] - orders['created_at']).dt.days

orders[['created_at', 'shipped_at', 'delai']].head()

           created_at          shipped_at  delai
0 2023-03-15 00:52:04 2023-03-17 00:52:04    2.0
1 2024-06-29 13:30:52 2024-07-02 13:30:52    3.0
2 2024-02-17 14:38:01 2024-02-19 14:38:01    2.0
3 2024-08-01 21:04:12                 NaT    NaN
4 2023-12-23 09:01:16 2023-12-24 09:01:16    1.0

# Quel est le délai de livraison moyen ? Testez avec .mean()

In [ ]:
delai_moyen = orders['delai']."METHODE"()
print(delai_moyen)

## 5. Trier les données

### Trier par valeurs

In [122]:
# Selon vous, que fait cette fonction? A quoi correspond l'argument 'ascending'
products.sort_values('retail_price', ascending=False).head(10)

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
1493,1494,Hurley Essential Suits & Sport Coats,Suits & Sport Coats,Hurley,Women,198.17,512.19,SKU-01494,5
1787,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
600,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
1247,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
298,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9
1977,1978,Diesel Modern Suits & Sport Coats,Suits & Sport Coats,Diesel,Men,172.04,461.81,SKU-01978,1
1489,1490,Tommy Hilfiger Original Suits & Sport Coats,Suits & Sport Coats,Tommy Hilfiger,Men,168.12,454.79,SKU-01490,10
142,143,Levi's Sport Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,153.02,446.66,SKU-00143,9
440,441,True Religion Regular Fit Suits & Sport Coats,Suits & Sport Coats,True Religion,Men,167.97,446.63,SKU-00441,2
1641,1642,Volcom Classic Suits & Sport Coats,Suits & Sport Coats,Volcom,Women,164.37,432.68,SKU-01642,6

### Trier par plusieurs colonnes

In [123]:
products.sort_values(['department', 'retail_price'], ascending=[True, False]).head(10)

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
1787,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
600,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
1247,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
298,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9
1977,1978,Diesel Modern Suits & Sport Coats,Suits & Sport Coats,Diesel,Men,172.04,461.81,SKU-01978,1
1489,1490,Tommy Hilfiger Original Suits & Sport Coats,Suits & Sport Coats,Tommy Hilfiger,Men,168.12,454.79,SKU-01490,10
142,143,Levi's Sport Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,153.02,446.66,SKU-00143,9
440,441,True Religion Regular Fit Suits & Sport Coats,Suits & Sport Coats,True Religion,Men,167.97,446.63,SKU-00441,2
211,212,Hurley Slim Fit Outerwear & Coats,Outerwear & Coats,Hurley,Men,141.69,413.60,SKU-00212,9
212,213,Volcom Slim Fit Outerwear & Coats,Outerwear & Coats,Volcom,Men,147.98,404.95,SKU-00213,3

### Réinitialiser l'index

In [124]:
# Après un tri ou un filtre, l'index est désorganisé. reset_index le remet à 0, 1, 2...
produits_tries = products.sort_values('retail_price', ascending=False)
produits_tries.reset_index(drop=True).head()

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
0,1494,Hurley Essential Suits & Sport Coats,Suits & Sport Coats,Hurley,Women,198.17,512.19,SKU-01494,5
1,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
2,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
3,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
4,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9

---
# Exercices pratiques

## Exercice 3.1 — L'Ingénieur de Features

### Questions
- Comment définissez vous le terme "features" ?
- Citez au moins 2 examples de features dont vous pouvez vous servir lors de la manipulation d'un dataset

### Pratique
Chargez `../01_data/exercises/thelook_sales.csv`. Créez ces colonnes:
1. `marge` = sale_price - cost
2. `mois` extrait de created_at (convertissez d'abord en datetime)
3. `is_premium` = True si sale_price > 100
4. `taux_marge` = (marge / sale_price) * 100

In [ ]:
# 1. Chargez le fichier et créez les colonnes marge et taux_marge
# Votre code ici

In [ ]:
# 2. Convertissez created_at et extrayez le mois
# Votre code ici

In [ ]:
# 3. Créez is_premium et affichez le pourcentage de ventes premium
# Votre code ici

## Exercice 3.2 — Le Nettoyeur de Noms
Chargez `../01_data/raw/thelook_products.csv`.
1. Mettez la colonne `name` en title case
2. Extrayez le premier mot du nom dans une colonne `marque`
3. Combien de produits contiennent le mot 'Slim' ?

In [ ]:
# 1 et 2. Title case + extraction marque
# Votre code ici

In [ ]:
# 3. Comptez les produits 'Sport'
# Votre code ici

## Exercice 3.3 — L'analyse temporel
Chargez `../01_data/raw/thelook_orders.csv`.
1. Convertissez created_at, shipped_at, delivered_at en datetime
2. Créez `delai_livraison` = delivered_at - created_at (en jours)
3. Quel est le délai moyen ? Varie-t-il selon le jour de la semaine ?

In [ ]:
# 1. Conversion des dates
# Votre code ici

In [ ]:
# 2. Calcul du délai
# Votre code ici

In [ ]:
# 3. Délai moyen et variation par jour
# Votre code ici